### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by klick** [bossanova808/CommerceFriendlyOrderNumbers#1]
Hey bossanova808 (and merry christmas).

I get a breaking Error after the user hits pay:

```
Undefined index: IsImageScience

/craft/plugins/commercefriendlyordernumbers/services/CommerceFriendlyOrderNumbersService.php(50)

50        if(craft()->config->get('environmentVariables')['IsImageScience']){
51             $order->setContentFromPost(array(
52                 'ISOrderNumber' => $orderNumber,
53             ));
54         }

```
It is looking for an environment variable of ”IsImageScience”. Do you know what that is?

Edit:
I have never used order fields. Do I have to put a reference to it into the checkout form?

Best
klick

**Comment by bossanova808** [comment]
Sorry, that's me being stupid.

Should be fixed by https://github.com/bossanova808/CommerceFriendlyOrderNumbers/releases/tag/0.0.3

**Comment by bossanova808** [comment]
(Oh and Merry Christmas too!)

**Comment by klick** [comment]
Thank you. Works as expected now. :)

**Comment by klick** [comment]
One more: I had to start-lowercase all `FriendlyOrderNumber` variable names in that jQuery-function in order for the friendly order number to show up on order detail-views in commerce. Otherwise it’s `#undefined`.

**Comment by bossanova808** [comment]
Cool, I'll update the docs - will be on holiday for a little while though (feel free to PR it!) :)
